name: basic_components
description: "A collection of basic components"
version: 0.0.15
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  better_components:
    git:
      url: https://github.com/Order-of-Runes/better_components.git
      ref: 0.0.4
  flutter:
    sdk: flutter
  morf:
    git:
      url: https://github.com/TheMakersPrime/morf.git
      ref: 0.0.3
  utils:
    git:
      url: https://github.com/Order-of-Runes/utils.git
      ref: 0.0.6

dev_dependencies:
  very_good_analysis: ^10.0.0